# -*- coding: utf-8 -*-
"""Trabajo_TICS_MRUA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WJJhQJvOtAJppAZxKAqQcwRyqi9HnPO3

**Trabajo TICS - MRUA**
**Graciela Rojas Silva**
"""

!sudo apt update
!sudo apt install libcairo2-dev \
    texlive texlive-latex-extra texlive-fonts-extra \
    texlive-latex-recommended texlive-science \
    tipa libpango1.0-dev
!pip install manim
!pip install IPython==8.21.0

"""**Importar Manim:**"""

from manim import *

"""**Paleta de colores**"""

COLOR_POS = BLUE
COLOR_VEL = GREEN
COLOR_ACC = YELLOW
COLOR_TXT = WHITE
COLOR_EJE = GRAY

"""**Escenas del video**

***S1 Apertura***
"""

class S1_Apertura(Scene):
    def construct(self):
        #Ruta del audio y la portada en Drive
        ruta_del_audio = "../assets/audio/S1 Apertura.m4a"
        ruta_de_la_portada = "../assets/imagenes/rickandmorty.png"

        #Audio e imagen
        try:
            self.add_sound(ruta_del_audio)
        except:
            print("Error: No se pudo encontrar el archivo de audio. Revisa la ruta.")

        try:
            portada = ImageMobject(ruta_de_la_portada)
            portada.set_height(config.frame_height)
            self.add(portada)
        except:
            fondo_error = Rectangle(width=config.frame_width, height=config.frame_height, fill_color=DARK_GREY, fill_opacity=1)
            txt_error = Text("Error: Revisa la ruta de la portada", color=RED)
            self.add(fondo_error, txt_error)
            self.wait(2)
            return

        #Código de animación (13 segundos)
        titulo = Text("Entendiendo el MRUA", font_size=60, weight=BOLD)
        titulo.set_stroke(BLACK, width=8, opacity=0.7)
        pregunta = Text("¿Cómo describimos el movimiento de un cohete al despegar?", font_size=32)
        pregunta.set_stroke(BLACK, width=8, opacity=0.7)

        # Agrupar el texto
        grupo_texto = VGroup(titulo, pregunta).arrange(DOWN, buff=0.5)
        grupo_texto.move_to(UP * 2)

        #Suma de tiempos para que encajen con el audio

        # 0s a 1s (Duración 1.0s)
        self.play(FadeIn(portada, scale=1.1), run_time=1.0)

        # 1s a 3s (Duración 2.0s): Aparece el título
        self.play(Write(titulo), run_time=2.0)

        # 3s a 6s (Duración 3.0s)
        self.wait(3.0)

        # 6s a 9s (Duración 3.0s): Aparece la pregunta
        self.play(FadeIn(pregunta), run_time=3.0)

        # 9s a 12s (Duración 3.0s)
        self.wait(3.0)

        # 12s a 13s (Duración 1.0s): Fade Out.
        self.play(FadeOut(portada), FadeOut(grupo_texto), run_time=1.0)

# Commented out IPython magic to ensure Python compatibility.
# #S1 (Apertura)
# %%manim -v WARNING -pqh S1_Apertura

"""***S2 Objetivos***"""

class S2_Objetivos(Scene):
    def construct(self):
        #Fondo azul
        self.camera.background_color = "#000080"

        #Ruta del audio en Drive
        ruta_del_audio_s2 = "../assets/audio/S2 Objetivos.m4a"
        try:
            self.add_sound(ruta_del_audio_s2)
        except:
            print("Error: No se pudo encontrar el archivo de audio S2. Revisa la ruta.")

            self.add(Text("Error: No se encontró el audio S2", color=RED))
            self.wait(2)
            return

        #Objetivo General
        titulo_general = Text("Objetivo de la clase", font_size=40, weight=BOLD, color=GREEN)
        titulo_general.to_edge(UP, buff=0.7)

        obj_general_txt = VGroup(
            Text("Visualizar y conectar las ecuaciones del MRUA", font_size=28),
            Text("con sus representaciones gráficas (posición, velocidad y aceleración).", font_size=28)
        ).arrange(DOWN, buff=0.15).next_to(titulo_general, DOWN, buff=0.3)

        #Objetivos Específicos
        titulo_especificos = Text("¿Qué aprenderemos hoy?", font_size=32, weight=BOLD, color=PURPLE)
        titulo_especificos.next_to(obj_general_txt, DOWN, buff=0.7)

        #Bullet por separado animado
        b1 = Text("1. La definición de MRUA.", font_size=28)
        b2 = Text("2. La diferencia entre el MRUA y el MRU.", font_size=28)
        b3 = Text("3. Las ecuaciones, variables y unidades de medida.", font_size=28)
        b4 = Text("4. Interpretar los tres gráficos del MRUA.", font_size=28)
        b5 = Text("5. Aplicar lo aprendido en un problema.", font_size=28)

        #Lista de los objetivos agrupada
        lista_especificos = VGroup(b1, b2, b3, b4, b5).arrange(
            DOWN, buff=0.2, aligned_edge=LEFT
        ).next_to(titulo_especificos, DOWN, buff=0.3, aligned_edge=LEFT)

        #Fade out final
        grupo_total = VGroup(titulo_general, obj_general_txt, titulo_especificos, lista_especificos)

        #Suma de tiempos para que encajen con el audio (46 segundos)

        # 0s - 1s (Duración 1.0s): Pausa inicial
        self.wait(1.0)

        # 1s - 4s (Duración 3.0s): Título
        self.play(Write(titulo_general), run_time=3.0)

        # 4s - 13s (Duración 9.0s): Objetivo general
        self.play(Write(obj_general_txt), run_time=9.0)

        # 13s - 14s (Duración 1.0s): Pausa
        self.wait(1.0)

        # 14s - 16s (Duración 2.0s): Pregunta
        self.play(Write(titulo_especificos), run_time=2.0)

        # 16s - 20s (Duración 4.0s): Objetivo específico 1
        self.play(Write(b1), run_time=4.0)

        # 20s - 26s (Duración 6.0s): Objetivo específico 2
        self.play(Write(b2), run_time=6.0)

        # 26s - 32s (Duración 6.0s): Objetivo específico 3
        self.play(Write(b3), run_time=6.0)

        # 32s - 39s (Duración 7.0s): Objetivo específico 4
        self.play(Write(b4), run_time=7.0)

        # 39s - 45s (Duración 6.0s): Objetivo específico 5
        self.play(Write(b5), run_time=6.0)

        # 45s - 46s (Duración 1.0s): Fade Out
        self.play(FadeOut(grupo_total), run_time=1.0)

# Commented out IPython magic to ensure Python compatibility.
# #S2 (Objetivos)
# %%manim -v WARNING -pqh S2_Objetivos

"""***S3a Definición de MRUA***:"""

class S3_DefinicionMRUA(Scene):
    def construct(self):
        #Fondo azul
        self.camera.background_color = "#000080"

        #Ruta del audio en Drive
        ruta_del_audio_s3 = "../assets/audio/S3 Definición.m4a"
        try:
            self.add_sound(ruta_del_audio_s3)
        except:
            print("Error: No se pudo encontrar el archivo de audio S3. Revisa la ruta.")
            self.add(Text("Error: No se encontró el audio S3", color=RED))
            self.wait(2)
            return

        #Textos
        intro_text = Text("Comencemos con lo básico", font_size=40).to_edge(UP)
        titulo = Text("¿Qué es el MRUA?", font_size=48, weight=BOLD).to_edge(UP)

        subtitulo = Text("Movimiento Rectilíneo Uniformemente Acelerado", font_size=30, color=GREEN)
        subtitulo.next_to(titulo, DOWN, buff=0.7)
        subtitulo.to_edge(LEFT, buff=1.0)

        claves_titulo = Text("Su nombre nos da 3 pistas claves:", font_size=28)
        claves_titulo.next_to(subtitulo, DOWN, buff=0.7)

        b1 = Text("1. Es Rectilíneo: Su trayectoria es una línea recta.", font_size=24, color=PURPLE)
        b2 = Text("2. Es Uniformemente Acelerado: su aceleración es constante y distinta de cero.", font_size=24, color=PURPLE)
        b3 = Text("3. Como la aceleración existe, su velocidad siempre está cambiando.", font_size=24, color=PURPLE)

        claves_lista = VGroup(b1, b2, b3).arrange(
            DOWN, buff=0.25, aligned_edge=LEFT
        ).next_to(claves_titulo, DOWN, buff=0.7)
        claves_lista.to_edge(LEFT, buff=1.0)

        g_texto = VGroup(subtitulo, claves_titulo, claves_lista)
        grupo_total = VGroup(titulo, g_texto)

        #Suma de tiempos para que encaje con el audio (36 segundos)

        self.wait(1.0) # 0s - 1s

        self.play(Write(intro_text), run_time=2.0) # 1s - 3s

        self.play(ReplacementTransform(intro_text, titulo), run_time=2.0) # 3s - 5s

        self.wait(1.0) # 5s - 6s

        self.play(Write(subtitulo), run_time=5.0) # 6s - 11s

        self.play(Write(claves_titulo), run_time=3.0) # 11s - 14s

        self.play(Write(b1), run_time=5.0) # 14s - 19s

        # Bloque de 19s - 29s
        self.play(Write(b2), run_time=3.0) # 19s - 22s

        self.wait(7.0) # 22s - 29s

        # Bloque de 29s - 35s
        self.play(Write(b3), run_time=5.0)
        self.wait(1.0)

        # Bloque de 35s - 36s
        self.play(FadeOut(grupo_total), run_time=1.0)

# Commented out IPython magic to ensure Python compatibility.
# #S3a (Definicion MRUA)
# %%manim -v WARNING -pqh S3_DefinicionMRUA

"""***S3b MRUA v/s MRU***"""

class S3b_ConceptoBase(Scene):
    def construct(self):
      #Fondo azul
      self.camera.background_color = "#000080"

      #Ruta de audio en Drive
      ruta_del_audio_s3b = "../assets/audio/S3 MRUA vs MRU.m4a"
      try:
          self.add_sound(ruta_del_audio_s3b)
      except:
          print("Error: No se pudo encontrar el audio S3b. Revisa la ruta.")
          self.add(Text("Error: No se encontró el audio S3b", color=RED))
          self.wait(2)
          return

      #Título
      titulo = Text("MRU vs. MRUA").to_edge(UP)

      #Animación superior de MRU
      eje_mru = NumberLine(x_range=[-1, 7], length=10).move_to(UP*1.5) #Eje
      punto_mru = Dot(point=eje_mru.n2p(0), color=COLOR_POS) #Punto azul
      vec_v_mru = Vector(RIGHT*1.5, color=COLOR_VEL).next_to(punto_mru, UP, buff=0.2) #Vector de velocidad
      label_v_mru = MathTex("v = \\text{constante}", color=COLOR_VEL).next_to(vec_v_mru, UP)
      label_a_mru = MathTex("a = 0", color=COLOR_ACC).next_to(eje_mru, DOWN)
      mru_group = VGroup(eje_mru, punto_mru, vec_v_mru, label_v_mru, label_a_mru)

      #Animación inferior de MRUA
      eje_mrua = NumberLine(x_range=[-1, 7], length=10).move_to(DOWN*1.5) #Eje
      punto_mrua = Dot(point=eje_mrua.n2p(0), color=COLOR_POS) #Punto azul
      vec_v_mrua = Vector(RIGHT*0.1, color=COLOR_VEL).next_to(punto_mrua, UP, buff=0.2) #Vector velocidad
      vec_a_mrua = Vector(RIGHT*1.0, color=COLOR_ACC).next_to(punto_mrua, DOWN, buff=0.2) #Vector aceleración
      label_v_mrua = MathTex("v = \\text{variable}", color=COLOR_VEL).next_to(vec_v_mrua, UP)
      label_a_mrua = MathTex("a = \\text{constante} \\neq 0", color=COLOR_ACC).next_to(vec_a_mrua, DOWN)
      mrua_group = VGroup(eje_mrua, punto_mrua, vec_v_mrua, vec_a_mrua, label_v_mrua, label_a_mrua)

      #Suma de tiempos para que encaje con el audio (25 segundos)

      # 0s - 1s: Pausa inicial
      self.wait(1.0)

      # 1s - 8s
      # Audio: "Ahora que ya sabemos qué es, comparemos..."
      self.play(Write(titulo), run_time=2.0)
      self.play(
          FadeIn(mru_group, shift=DOWN),
          FadeIn(mrua_group, shift=UP),
          run_time = 5.0
        )

      # 8s - 17s (Duración 9.0s):
      # Audio: "En el movimiento rectilíneo uniforme..."
      self.wait(9.0)

      #Definición de Updaters (animación del vector)
      def v_updater(mob):
          pos = eje_mrua.p2n(punto_mrua.get_center())
          new_len = 0.1 + 0.5 * pos
          if new_len < 0.1: new_len = 0.1
          if new_len > 3.0: new_len = 3.0
          mob.become(
            Vector(RIGHT*new_len, color=COLOR_VEL).next_to(punto_mrua, UP, buff=0.2)
       )
          label_v_mrua.next_to(mob, UP) # La etiqueta sigue al vector

      vec_v_mrua.add_updater(v_updater)
      vec_v_mru.add_updater(lambda m: m.next_to(punto_mru, UP, buff=0.2))
      label_v_mru.add_updater(lambda m: m.next_to(vec_v_mru, UP, buff=0.1))
      vec_a_mrua.add_updater(lambda m: m.next_to(punto_mrua, DOWN, buff=0.2))
      label_a_mrua.add_updater(lambda m: m.next_to(vec_a_mrua, DOWN, buff=0.1))

      # 17s - 24s
      # Audio: "Pero, en el MRUA, la velocidad cambia..."
      # Animación de los puntos
      self.play(
          punto_mru.animate.move_to(eje_mru.n2p(6)),
          punto_mrua.animate.move_to(eje_mrua.n2p(6)),
          run_time = 7.0,
          rate_func = linear
      )
      # Limpieza updaters
      vec_v_mrua.clear_updaters()
      vec_v_mru.clear_updaters()
      label_v_mru.clear_updaters()
      vec_a_mrua.clear_updaters()
      label_a_mrua.clear_updaters()

      # 24s - 25s
      # Audio: (pausa)
      # Animación de salida
      self.play(FadeOut(mru_group), FadeOut(mrua_group), FadeOut(titulo), run_time = 1.0)

# Commented out IPython magic to ensure Python compatibility.
# #S3b (MRUA vs MRU)
# %%manim -v WARNING -pqh S3b_ConceptoBase

"""***S4 Ecuaciones***"""

class S4_ModeloEcuaciones(Scene):
    def construct(self):
        #Fondo azul
        self.camera.background_color = "#000080"

        #Ruta del audio en Drive
        ruta_del_audio_s4 = "../assets/audio/S4 Ecuaciones.m4a"
        try:
            self.add_sound(ruta_del_audio_s4)
        except:
            print("Error: No se pudo encontrar el archivo de audio S4. Revisa la ruta.")
            self.add(Text("Error: No se encontró el audio S4", color=RED))
            self.wait(2)
            return

        # Variable para llevar la cuenta del tiempo
        manim_time = 0.0

        #Textos
        titulo = Text("Las Ecuaciones del MRUA", color=GREEN).to_edge(UP)
        stack_anchor = (RIGHT * 4) + (UP * 2) # Ancla para eqs en la derecha

        # Definiciones de Ecuaciones
        eq1 = MathTex("v_f = v_i + a \\cdot t", font_size=52, color=YELLOW)
        eq1.move_to(LEFT*2.5 + UP*1.5)
        defs1 = VGroup(
            MathTex("v_f: \\text{ Velocidad final (m/s)}", font_size=36),
            MathTex("v_i: \\text{ Velocidad inicial (m/s)}", font_size=36),
            MathTex("a: \\text{ Aceleración (m/s²)}", font_size=36),
            MathTex("t: \\text{ Tiempo (s)}", font_size=36)
        ).arrange(DOWN, buff=0.2, aligned_edge=LEFT).next_to(eq1, DOWN, buff=0.5, aligned_edge=LEFT)
        g1 = VGroup(eq1, defs1)

        eq2 = MathTex("d = v_i \\cdot t + \\frac{1}{2} a \\cdot t^2", font_size=52, color=YELLOW)
        eq2.move_to(LEFT*2.5 + UP*1.5)
        defs2 = VGroup(
            MathTex("d: \\text{ Distancia o posición final (m)}", font_size=36),
            MathTex("\\text{(Asumiendo } d_i = 0 \\text{ m)}", font_size=28, color=RED),
            MathTex("v_i: \\text{ Velocidad inicial (m/s)}", font_size=36),
            MathTex("a: \\text{ Aceleración (m/s²)}", font_size=36),
            MathTex("t: \\text{ Tiempo (s)}", font_size=36)
        ).arrange(DOWN, buff=0.2, aligned_edge=LEFT).next_to(eq2, DOWN, buff=0.5, aligned_edge=LEFT)
        g2 = VGroup(eq2, defs2)

        eq3 = MathTex("v_f^2 = v_i^2 + 2 a d", font_size=52, color=YELLOW)
        eq3.move_to(LEFT*2.5 + UP*1.5)
        defs3 = VGroup(
            MathTex("v_f: \\text{ Velocidad final (m/s)}", font_size=36),
            MathTex("v_i: \\text{ Velocidad inicial (m/s)}", font_size=36),
            MathTex("a: \\text{ Aceleración (m/s²)}", font_size=36),
            MathTex("d: \\text{ Distancia (m)}", font_size=36)
        ).arrange(DOWN, buff=0.2, aligned_edge=LEFT).next_to(eq3, DOWN, buff=0.5, aligned_edge=LEFT)
        g3 = VGroup(eq3, defs3)

        #Suma de tiempos para que encaje con el audio (1m y 42 segundos)

        #"Como en el MRUA..."
        self.wait(1.0)
        manim_time = 1.0

        self.play(Write(titulo), run_time=2.0)
        manim_time += 2.0 # manim_time = 3.0s

        #"La primera ecuación..."
        wait_1 = 9.0 - manim_time
        self.wait(wait_1) # Espera de 6.0s
        manim_time = 9.0

        #"La velocidad final es igual a…"
        wait_2 = 13.0 - manim_time
        self.wait(wait_2) # Espera de 4.0s
        manim_time = 13.0

        rt_eq1 = 2.0
        self.play(Write(eq1), run_time=rt_eq1)
        manim_time += rt_eq1 # manim_time = 15.0s

        #"Donde vf…"
        wait_3 = 19.0 - manim_time
        self.wait(wait_3) # Espera de 4.0s
        manim_time = 19.0

        rt_defs1 = 3.0
        self.play(Write(defs1), run_time=rt_defs1)
        manim_time += rt_defs1 # manim_time = 22.0s

        #"La segunda ecuación..."
        wait_4 = 42.0 - manim_time
        self.wait(wait_4) # Pausa larga de 20.0s para explicar Eq1
        manim_time = 42.0

        eq1_small = eq1.copy().scale(0.7).move_to(stack_anchor)
        rt_g2 = 2.0
        self.play(
            ReplacementTransform(g1, g2),
            FadeIn(eq1_small, shift=LEFT),
            run_time=rt_g2
        )
        manim_time += rt_g2 # manim_time = 44.0s

        #"Aquí d es la distancia..."
        wait_5 = 79.0 - manim_time
        self.wait(wait_5) # Pausa larga de 35.0s para explicar Eq2
        manim_time = 79.0

        eq2_small = eq2.copy().scale(0.7).next_to(eq1_small, DOWN, buff=0.5, aligned_edge=RIGHT)
        rt_g3 = 2.0
        self.play(
            ReplacementTransform(g2, g3),
            FadeIn(eq2_small, shift=LEFT),
            run_time=rt_g3
        )
        manim_time += rt_g3 # manim_time = 81.0s

        #"la velocidad final al cuadrado…"
        wait_6 = 101.0 - manim_time
        self.wait(wait_6) # Pausa larga de 20.0s para explicar Eq3
        manim_time = 101.0

        # Fade out final
        self.play(
            FadeOut(g3),
            FadeOut(eq1_small),
            FadeOut(eq2_small),
            FadeOut(titulo),
            run_time=1.0
        )

# Commented out IPython magic to ensure Python compatibility.
# #S4 (Ecuaciones)
# %%manim -v WARNING -pqh S4_ModeloEcuaciones

"""***S5a Gráficos***"""

class S5a_EjemplosGraficos(Scene):
    def construct(self):
        self.camera.background_color = "#000080"
        # S5. Ejemplos aplicados: Gráficos

        #Ruta del audio en Drive
        ruta_del_audio_s5a = "../assets/audio/S5 gráficas.m4a"
        try:
            self.add_sound(ruta_del_audio_s5a)
        except:
            print("Error: No se pudo encontrar el archivo de audio S5a. Revisa la ruta.")
            self.add(Text("Error: No se encontró el audio S5a", color=RED))
            self.wait(2)
            return

        # Variable para llevar la cuenta del tiempo
        manim_time = 0.0

        #Textos

        titulo = Text("Los 3 Gráficos del MRUA", color=GREEN).to_edge(UP)

        # Definimos un caso: a=0.5 m/s², v_i=1 m/s, d_i=0 m
        A = 0.5
        V_I = 1.0

        #Ejes de los graficos
        ejes_a = Axes(
            x_range=[0, 10, 2], y_range=[0, 2, 0.5],
            x_length=2.0, y_length=2.0, # Longitud de ejes
            axis_config={"color": COLOR_EJE, "include_tip": False},
            x_axis_config={"numbers_to_include": [10]},
            y_axis_config={"numbers_to_include": [A]}
        )

        ejes_v = Axes(
            x_range=[0, 10, 2], y_range=[0, 8, 2],
            x_length=2.0, y_length=2.0, # Longitud de ejes
            axis_config={"color": COLOR_EJE, "include_tip": False},
            x_axis_config={"numbers_to_include": [10]},
            y_axis_config={"numbers_to_include": [V_I]}
        )

        ejes_d = Axes(
            x_range=[0, 10, 2], y_range=[0, 40, 10],
            x_length=2.0, y_length=2.0, # Longitud de ejes
            axis_config={"color": COLOR_EJE, "include_tip": False},
            x_axis_config={"numbers_to_include": [10]},
            y_axis_config={"numbers_to_include": [10, 20, 30]}
        )

        # Etiquetas de los ejes
        label_a = ejes_a.get_axis_labels(x_label="t (s)", y_label="a (m/s²)")
        label_v = ejes_v.get_axis_labels(x_label="t (s)", y_label="v (m/s)")
        label_d = ejes_d.get_axis_labels(x_label="t (s)", y_label="d (m)")

        g_a = VGroup(ejes_a, label_a)
        g_v = VGroup(ejes_v, label_v)
        g_d = VGroup(ejes_d, label_d)

        #Grupo
        g_ejes = VGroup(g_a, g_v, g_d)
        g_ejes.arrange(RIGHT, buff=0.7) # Los organiza horizontalmente
        g_ejes.next_to(titulo, DOWN, buff=0.5) # Los centra debajo del título

        #Funciones
        graph_a = ejes_a.plot(lambda t: A, x_range=[0, 10], color=COLOR_ACC)
        graph_v = ejes_v.plot(lambda t: V_I + A*t, x_range=[0, 10], color=COLOR_VEL)
        graph_d = ejes_d.plot(lambda t: V_I*t + 0.5*A*t**2, x_range=[0, 10], color=COLOR_POS)

        #Descripciones
        desc_a = Text("Aceleración-Tiempo: \nRecta horizontal (constante)", font_size=20).next_to(g_a, DOWN, buff=0.2)
        desc_v = Text("Velocidad-Tiempo: \nRecta con pendiente (lineal)", font_size=20).next_to(g_v, DOWN, buff=0.2)
        desc_d = Text("Posición-Tiempo: \nParábola (cuadrática)", font_size=20).next_to(g_d, DOWN, buff=0.2)

        #Pendiente y área
        slope_v = ejes_v.get_secant_slope_group(
            x=2.0, graph=graph_v, dx=3.0,
            secant_line_length=3, secant_line_color=RED
        )
        slope_v_label = MathTex("\\text{Pendiente} = a", color=RED, font_size=30).next_to(slope_v, UP, buff=0.2)

        area_v = ejes_v.get_area(graph=graph_v, x_range=[0, 8], color=BLUE_E, opacity=0.5)
        area_v_label = MathTex("\\text{Área} = d", color=RED, font_size=30).move_to(ejes_v.c2p(4, 2))


        #Suma de tiempos para que encaje con el audio (60segundos)

        #"la mejor forma de ver el MRUA..."
        self.wait(1.0)
        manim_time = 1.0

        rt_titulo = 2.0
        self.play(Write(titulo), run_time=rt_titulo)
        manim_time += rt_titulo # manim_time = 3.0s

        #"por ejemplo... tenemos 3 tipos de gráficos."
        wait_1 = 9.0 - manim_time
        self.wait(wait_1)
        manim_time = 9.0

        rt_ejes = 3.0
        self.play(FadeIn(g_ejes), run_time=rt_ejes)
        manim_time += rt_ejes

        #"el primero, es el gráfico de aceleración..."
        wait_2 = 20.0 - manim_time
        self.wait(wait_2)
        manim_time = 20.0

        rt_ga = 2.0
        self.play(Create(graph_a), run_time=rt_ga)
        manim_time += rt_ga

        rt_da = 1.5
        self.play(Write(desc_a), run_time=rt_da)
        manim_time += rt_da

        #"el segundo gráfico... la pendiente... es la aceleración"
        wait_3 = 31.0 - manim_time
        self.wait(wait_3)
        manim_time = 31.0

        rt_gv = 2.0
        self.play(Create(graph_v), run_time=rt_gv)
        manim_time += rt_gv

        rt_dv = 1.5
        self.play(Write(desc_v), run_time=rt_dv)
        manim_time += rt_dv

        #Pendiente justo después de describir el gráfico
        rt_slope = 2.0
        self.play(Create(slope_v), Write(slope_v_label), run_time=rt_slope)
        manim_time += rt_slope

        #"Además, el área debajo esta curva..."
        wait_4 = 45.0 - manim_time
        self.wait(wait_4)
        manim_time = 45.0

        rt_area = 2.5
        self.play(FadeOut(slope_v), FadeOut(slope_v_label),
                  FadeIn(area_v), Write(area_v_label), run_time=rt_area)
        manim_time += rt_area

        #"El último gráfico, es el de posición..."
        wait_5 = 51.0 - manim_time
        self.wait(wait_5)
        manim_time = 51.0

        rt_gd = 2.0
        self.play(Create(graph_d), run_time=rt_gd)
        manim_time += rt_gd

        rt_dd = 1.5
        self.play(Write(desc_d), run_time=rt_dd)
        manim_time += rt_dd

        #Fin del audio
        wait_6 = 60.0 - manim_time
        self.wait(wait_6)
        manim_time = 60.0

        # Fade out final
        self.play(
            FadeOut(VGroup(titulo, g_ejes, graph_a, graph_v, graph_d)),
            FadeOut(VGroup(desc_a, desc_v, desc_d, area_v, area_v_label)),
            run_time=1.0
        )

# Commented out IPython magic to ensure Python compatibility.
# #S5a (Gráficos)
# %%manim -v WARNING -pqh S5a_EjemplosGraficos

"""***S5b Ejercicio***"""

class S5b_Ejercicio(Scene):
    def construct(self):
        self.camera.background_color = "#000080"

        #Ruta audio en el Drive
        ruta_del_audio_s5b = "../assets/audio/S5 ejercicio.m4a"
        try:
            self.add_sound(ruta_del_audio_s5b)
        except:
            print("Error: No se pudo encontrar el archivo de audio S5b. Revisa la ruta.")
            self.add(Text("Error: No se encontró el audio S5b", color=RED))
            self.wait(2)
            return

        # Variable para llevar la cuenta del tiempo
        manim_time = 0.0

        #Textos
        titulo_app = Text("Aplicación: Problema MRUA", font_size=40, color=GREEN).to_edge(UP)

        # Elementos del Problema
        datos_titulo = Text("Datos del Problema:", font_size=32).to_edge(UL, buff=1.0).shift(DOWN*0.5)
        dato_v = MathTex("v_i = 1 \\text{ m/s}", font_size=32).next_to(datos_titulo, DOWN, aligned_edge=LEFT, buff=0.4)
        dato_a = MathTex("a = 0.5 \\text{ m/s}^2", font_size=32).next_to(dato_v, DOWN, aligned_edge=LEFT, buff=0.4)
        dato_t = MathTex("t = 8 \\text{ s}", font_size=32).next_to(dato_a, DOWN, aligned_edge=LEFT, buff=0.4)

        pregunta_d = MathTex("d = ?", font_size=40, color=YELLOW).next_to(dato_t, DOWN, aligned_edge=LEFT, buff=0.6)

        g_problema = VGroup(datos_titulo, dato_v, dato_a, dato_t, pregunta_d)

        # Elementos de Solución 1 (Ecuación)
        sol_1_titulo = Text("Solución 1: Ecuación de Posición", font_size=32, color=PURPLE).to_edge(UL, buff=1.0).shift(DOWN*0.5)

        eq_pos = MathTex("d = v_i \\cdot t + \\frac{1}{2} a \\cdot t^2", font_size=36)
        eq_pos.next_to(sol_1_titulo, DOWN, buff=0.5, aligned_edge=LEFT)

        eq_reemplazada = MathTex("d = (1 \\text{ m/s})(8 \\text{ s}) + \\frac{1}{2} (0.5 \\text{ m/s}^2)(8 \\text{ s})^2", font_size=36)
        eq_reemplazada.next_to(sol_1_titulo, DOWN, buff=0.5, aligned_edge=LEFT)

        eq_paso1 = MathTex("d = 8 \\text{ m} + \\frac{1}{2} (0.5 \\text{ m/s}^2)(64 \\text{ s}^2)", font_size=36)
        eq_paso1.next_to(sol_1_titulo, DOWN, buff=0.5, aligned_edge=LEFT)

        eq_paso2 = MathTex("d = 8 \\text{ m} + 16 \\text{ m}", font_size=36)
        eq_paso2.next_to(sol_1_titulo, DOWN, buff=0.5, aligned_edge=LEFT)

        eq_final = MathTex("d = 24 \\text{ m}", font_size=40, color=GREEN)
        eq_final.next_to(sol_1_titulo, DOWN, buff=0.5, aligned_edge=LEFT)

        g_sol_1 = VGroup(sol_1_titulo, eq_pos)

        # Elementos de Solución 2 (Gráfico)
        sol_2_titulo = Text("Solución 2: Gráfico v-t", font_size=32, color=PURPLE).to_edge(UL, buff=1.0).shift(DOWN*0.5)
        ejes_v = Axes(
            x_range=[0, 10, 2], y_range=[0, 8, 2],
            x_length=6.0, y_length=4.0,
            axis_config={"color": BLUE, "include_tip": False},
        ).next_to(sol_2_titulo, DOWN, buff=0.5).to_edge(RIGHT, buff=1.5)

        label_v = ejes_v.get_axis_labels(x_label="t (s)", y_label="v (m/s)")

        A = 0.5
        V_I = 1.0
        graph_v = ejes_v.plot(lambda t: V_I + A*t, x_range=[0, 10], color=YELLOW)

        area_v = ejes_v.get_area(graph=graph_v, x_range=[0, 8], color=BLUE_E, opacity=0.5)
        area_v_label = MathTex("\\text{Área} = d = 24 \\text{ m}", color=RED, font_size=36)
        area_v_label.move_to(ejes_v.c2p(4, 2))

        g_sol_2 = VGroup(sol_2_titulo, ejes_v, label_v, graph_v, area_v, area_v_label)


        #Suma de tiempos (102s)

        #"Ahora es momento..."
        self.wait(1.0)
        manim_time = 1.0

        rt_titulo = 2.0
        self.play(Write(titulo_app), run_time=rt_titulo)
        manim_time += rt_titulo # manim_time = 3.0s

        #"Un móvil parte..." (Datos)
        wait_1 = 13.0 - manim_time
        self.wait(wait_1) # Espera de 10.0s
        manim_time = 13.0

        rt_datos = 3.0 # Escribir v_i y a
        self.play(Write(datos_titulo), run_time=1.0)
        self.play(Write(dato_v), run_time=1.0)
        self.play(Write(dato_a), run_time=1.0)
        manim_time += rt_datos # manim_time = 16.0s

        #"Entonces, ¿qué distancia..." (Pregunta)
        wait_2 = 24.0 - manim_time
        self.wait(wait_2) # Espera de 8.0s
        manim_time = 24.0

        rt_preg = 2.0 # Escribir t y d=?
        self.play(Write(dato_t), run_time=1.0)
        self.play(Write(pregunta_d), run_time=1.0)
        manim_time += rt_preg # manim_time = 26.0s

        #Pausa
        wait_3 = 31.0 - manim_time
        self.wait(wait_3) # Espera de 5.0s
        manim_time = 31.0

        #"primero... ecuación de posicion..." (Ecuación)
        rt_sol1 = 3.0
        self.play(
            ReplacementTransform(datos_titulo, sol_1_titulo),
            FadeOut(VGroup(dato_v, dato_a, dato_t, pregunta_d)),
            run_time=1.0
        )
        self.play(Write(eq_pos), run_time=2.0)
        manim_time += rt_sol1 # manim_time = 34.0s

        #"Si reemplazamos los valores..." (Reemplazo)
        wait_4 = 46.0 - manim_time
        self.wait(wait_4) # Espera de 12.0s
        manim_time = 46.0

        rt_reemp = 2.0
        self.play(ReplacementTransform(eq_pos, eq_reemplazada), run_time=rt_reemp)
        manim_time += rt_reemp # manim_time = 48.0s

        #"Si resolvemos... 24 metros." (Cálculo)
        wait_5 = 65.0 - manim_time
        self.wait(wait_5) # Espera de 17.0s
        manim_time = 65.0

        rt_calc_1 = 2.0
        self.play(ReplacementTransform(eq_reemplazada, eq_paso1), run_time=rt_calc_1)
        manim_time += rt_calc_1 # manim_time = 67.0s

        rt_calc_2 = 2.0
        self.play(ReplacementTransform(eq_paso1, eq_paso2), run_time=rt_calc_2)
        manim_time += rt_calc_2 # manim_time = 69.0s

        rt_calc_3 = 2.0
        self.play(ReplacementTransform(eq_paso2, eq_final), run_time=rt_calc_3)
        manim_time += rt_calc_3 # manim_time = 71.0s

        self.play(Indicate(eq_final), run_time=1.5)
        manim_time += 1.5 # manim_time = 72.5s

        #Pausa
        wait_6 = 75.0 - manim_time
        self.wait(wait_6) # Espera de 2.5s
        manim_time = 75.0

        #"ahora, si graficamos..." (Gráfico)
        rt_sol2_setup = 3.0
        self.play(
            FadeOut(VGroup(sol_1_titulo, eq_final)),
            FadeIn(sol_2_titulo),
            FadeIn(ejes_v, label_v),
            run_time=rt_sol2_setup
        )
        manim_time += rt_sol2_setup # manim_time = 78.0s

        rt_sol2_graph = 4.0
        self.play(Create(graph_v), run_time=2.0)
        self.play(FadeIn(area_v), Write(area_v_label), run_time=2.0)
        manim_time += rt_sol2_graph # manim_time = 82.0s

        #Fin del audio
        wait_7 = 102.0 - manim_time
        self.wait(wait_7) # Espera de 20.0s
        manim_time = 102.0

        # Fade out final
        self.play(
            FadeOut(titulo_app),
            FadeOut(g_sol_2),
            run_time=1.0
        )
        self.wait(0.5)

# Commented out IPython magic to ensure Python compatibility.
# #S5b (Ejercicio aplicado)
# %%manim -v WARNING -pqh S5b_Ejercicio

"""***S6 Cierre***"""

class S6_Cierre(Scene):
    def construct(self):
        self.camera.background_color = "#000080"
        # S6. Cierre: Resumen + pregunta

        #Ruta audio en Drive
        ruta_del_audio_s6 = "../assets/audio/S6 Cierre.m4a"
        try:
            self.add_sound(ruta_del_audio_s6)
        except:
            print("Error: No se pudo encontrar el archivo de audio S6. Revisa la ruta.")
            self.add(Text("Error: No se encontró el audio S6", color=RED))
            self.wait(2)
            return

        # Variable para llevar la cuenta del tiempo
        manim_time = 0.0

        #Textos
        titulo = Text("Resumen", color=GREEN).to_edge(UP)
        resumen = BulletedList(
            "En el MRUA, la Aceleración es constante y distinta de cero.",
            "La Velocidad cambia de forma lineal (es una recta en el gráfico v-t).",
            "La Posición cambia de forma cuadrática (es una parábola en el gráfico d-t).",
            "Las ecuaciones y gráficos nos permiten predecir el movimiento.",
            font_size=34,
            buff=0.4
        ).next_to(titulo, DOWN, buff=0.7).to_edge(LEFT, buff=0.7) #to_edge para alinear

        # Pregunta para pensar
        pregunta = Text("Para pensar...", font_size=40, color=YELLOW).next_to(resumen, DOWN, buff=1.0)
        pregunta_txt = Text(
            "Si dejas caer una manzana, ignorando el roce del aire, \n¿es un MRUA? ¿Cómo serían sus gráficos?",
            font_size=32,
            line_spacing=0.7
        ).next_to(pregunta, DOWN, buff=0.3)

        g_pregunta = VGroup(pregunta, pregunta_txt)
        g_pregunta.align_to(resumen, LEFT) # Alinear pregunta con el resumen

        #Suma de tiempos (38s)

        #"en resumen..."
        self.wait(1.0)
        manim_time = 1.0

        rt_titulo = 1.5
        self.play(Write(titulo), run_time=rt_titulo)
        manim_time += rt_titulo # manim_time = 2.5s

        #"...la aceleracion es constante, ademas la velocidad cambia linealmente"
        rt_res1_2 = 5.0
        self.play(
            Write(VGroup(resumen[0], resumen[1])), # Escribir los primeros 2 puntos
            run_time=rt_res1_2
        )
        manim_time += rt_res1_2 # manim_time = 7.5s

        wait_1 = 14.0 - manim_time
        self.wait(wait_1) # Espera de 6.5s
        manim_time = 14.0

        #"tambien la posicion cambia... conectados"
        rt_res3_4 = 5.0
        self.play(
            Write(VGroup(resumen[2], resumen[3])), # Escribir los últimos 2 puntos
            run_time=rt_res3_4
        )
        manim_time += rt_res3_4 # manim_time = 19.0s

        wait_2 = 24.0 - manim_time
        self.wait(wait_2) # Espera de 5.0s
        manim_time = 24.0

        #"ahora… para pensar"
        rt_preg = 1.5
        self.play(Write(pregunta), run_time=rt_preg)
        manim_time += rt_preg # manim_time = 25.5s

        wait_3 = 27.0 - manim_time
        self.wait(wait_3) # Espera de 1.5s
        manim_time = 27.0

        #"si dejas caer una manzana..."
        rt_preg_txt = 5.0
        self.play(Write(pregunta_txt), run_time=rt_preg_txt)
        manim_time += rt_preg_txt # manim_time = 32.0s

        wait_4 = 38.0 - manim_time
        self.wait(wait_4) # Espera de 6.0s
        manim_time = 38.0

        print(f"Duración total de la animación (antes del fade): {manim_time} segundos")

        # Fade out final
        self.play(
            FadeOut(titulo),
            FadeOut(resumen),
            FadeOut(pregunta),
            FadeOut(pregunta_txt),
            run_time=1.0
        )
        self.wait(0.5)

# Commented out IPython magic to ensure Python compatibility.
# #S6 (Cierre)
# %%manim -v WARNING -pqh S6_Cierre

"""***S7 Créditos***"""

class S7_Creditos(Scene):
    def construct(self):
        self.camera.background_color = "#000080"

        # AÑADIR AUDIO DE FONDO (10s)
        ruta_audio_fondo = "../assets/audio/audiocreditos.mp3"
        try:
            self.add_sound(ruta_audio_fondo)
        except:
            print("Error: No se pudo encontrar el archivo de audio de fondo.")
            self.add(Text("Error: Audio no encontrado", color=RED, font_size=24).to_corner(DR))

        #ELEMENTOS
        titulo = Text("Créditos", font_size=48).to_edge(UP)

        linea1 = Text("Video realizado por:", font_size=32).shift(UP*1.8)

        #ruta exacta a tu archivo de imagen
        ruta_icono_profesora = "/content/drive/MyDrive/Utalca/3er año/2do semestre/Tics manim/profesora.png"
        try:
            icono = ImageMobject(ruta_icono_profesora)
            icono.set(height=1.5) # Ajusta el tamaño
            icono.shift(UP * 0.5) # Posición entre linea1 y linea2
            mostrar_icono = True
        except:
            print("Error: No se pudo encontrar la imagen del icono.")
            icono = Text("Error: Imagen no encontrada", color=RED, font_size=24).shift(UP * 0.5)
            mostrar_icono = False # No animar si no se cargó

        linea2 = Text("Graciela Rojas Silva", font_size=36, weight=BOLD)
        linea2.shift(DOWN * 0.7) # Mover más abajo

        linea3 = Text("Asignatura: TICS ", font_size=28).shift(DOWN*1.8)
        linea4 = Text("Software: Manim (Manim Community v0.19.0) en Google Colab", font_size=28).shift(DOWN*2.5)
        linea5 = Text("Universidad de Talca, 2025", font_size=30).shift(DOWN*3.2)

        # Usar Group en lugar de VGroup.
        # ImageMobject no es un VMobject, por lo que no puede ir en un VGroup.
        # Group es un contenedor genérico que acepta CUALQUIER tipo de Mobject.
        g_creditos = Group(titulo, linea1, icono, linea2, linea3, linea4, linea5)

        #Suma de tiempos (Total 10s + FadeOut)

        # Tiempo 0.0s - 1.0s
        self.play(Write(titulo), run_time=1.0)

        # Tiempo 1.0s - 1.75s
        self.play(FadeIn(linea1, shift=UP), run_time=0.75)

        # Tiempo 1.75s - 2.5s
        if mostrar_icono:
            self.play(FadeIn(icono, scale=0.5), run_time=0.75)
        else:
            self.play(Write(icono), run_time=0.75) # Muestra el error

        # Tiempo 2.5s - 3.25s
        self.play(FadeIn(linea2, shift=DOWN), run_time=0.75)

        # Tiempo 3.25s - 4.75s
        self.play(
            FadeIn(linea3, shift=DOWN),
            FadeIn(linea4, shift=DOWN),
            FadeIn(linea5, shift=DOWN),
            run_time=1.5
        )

        # La animación dura 4.75s hasta ahora.
        # El audio dura 10s.
        tiempo_restante = 10.0 - 4.75

        # Tiempo 4.75s - 10.0s
        self.wait(tiempo_restante) # Espera de 5.25s

        # Tiempo 10.0s - 11.0s
        self.play(
            FadeOut(g_creditos), # Ahora esto funcionará
            run_time=1.0
        )
        self.wait(0.5) # Pequeña pausa final

# Commented out IPython magic to ensure Python compatibility.
# #S7 (Créditos)
# %%manim -v WARNING -pqh S7_Creditos

"""**Video completo**"""

# Commented out IPython magic to ensure Python compatibility.
# %%shell
# 
# # PASO 1: Crear la lista de videos (usando tus 9 rutas)
# echo "file '/content/media/videos/content/1080p60/S1_Apertura.mp4'" > lista_videos.txt
# echo "file '/content/media/videos/content/1080p60/S2_Objetivos.mp4'" >> lista_videos.txt
# echo "file '/content/media/videos/content/1080p60/S3_DefinicionMRUA.mp4'" >> lista_videos.txt
# echo "file '/content/media/videos/content/1080p60/S3b_ConceptoBase.mp4'" >> lista_videos.txt
# echo "file '/content/media/videos/content/1080p60/S4_ModeloEcuaciones.mp4'" >> lista_videos.txt
# echo "file '/content/media/videos/content/1080p60/S5a_EjemplosGraficos.mp4'" >> lista_videos.txt
# echo "file '/content/media/videos/content/1080p60/S5b_Ejercicio.mp4'" >> lista_videos.txt
# echo "file '/content/media/videos/content/1080p60/S6_Cierre.mp4'" >> lista_videos.txt
# echo "file '/content/media/videos/content/1080p60/S7_Creditos.mp4'" >> lista_videos.txt
# 
# echo "--- Lista de videos creada. ---"
# 
# # PASO 2: Unir los videos con ffmpeg
# ffmpeg -f concat -safe 0 -i lista_videos.txt -c copy /content/video_completo_MRUA.mp4
# 
# echo ""
# echo "****************************************************************"
# echo "¡ÉXITO! Se ha creado 'video_completo_MRUA.mp4' en /content/"
# echo "****************************************************************"

from IPython.display import HTML
from base64 import b64encode
import os

# Ruta al video que acabamos de crear
ruta_video = "/content/video_completo_MRUA.mp4"

# Comprobamos si el archivo existe
if not os.path.exists(ruta_video):
    print(f"¡Error! No se encontró el archivo en: {ruta_video}")
    print("Asegúrate de haber ejecutado la celda anterior (%%shell) sin errores.")
else:
    # Leemos el video y lo preparamos para mostrarlo
    mp4 = open(ruta_video, 'rb').read()
    data_url = "data:video/mp4;base64," + b64encode(mp4).decode()

    # Mostramos el reproductor de video en la celda
    print(f"Mostrando video: {ruta_video}")
    display(HTML(f"""
    <video width=800 controls style="border:1px solid #CCC; border-radius: 8px;">
        <source src="{data_url}" type="video/mp4">
    </video>
    """))